### ISSUE TITLE
Later Binding on specific file does not work

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#1005]
**Describe the bug**
The GOOSE type later binding plugin does not show any `ExtRef` when clicking on data

**To Reproduce**
Open appending file
1. Go to Subscribe - Later Binding (GOOSE)
2. Click on '´data'
3. See no reaction in possible inputs

**Expected behavior**
A selection of inputs or a warning that there are none

**Additional context**
See file
[LaterBindingGOOSEError.scd.zip](https://github.com/openscd/open-scd/files/9584092/LaterBindingGOOSEError.scd.zip)

**Comment by danyill** [comment]
I have the same issue for both GOOSE and SV when using Edition 2.1 with Siemens SIPROTEC 5 devices.

The attached scd may help reproduce this.

[XAT_Prot2_Base_Configuration.scd_1.zip](https://github.com/openscd/open-scd/files/9641602/XAT_Prot2_Base_Configuration.scd_1.zip)

**Comment by danyill** [comment]
@JakobVogelsang I'm a bit confused by your specific file. There is a single IED, and I would not expect there to be any possibility of subscribing to anything else. There are no ExtRefs in this file. 

![image](https://user-images.githubusercontent.com/674783/193392482-4e7c58c9-182c-4723-b98f-2a58eb46a76e.png)

What did I miss?

**Comment by danyill** [comment]
I thought I might try to diagnose the issue I'm having with Edition 2.1 DIGSI 5 SCL files. It is caused by:

https://github.com/openscd/open-scd/blob/48ef7ea26d772573027f9627612fb56e3a982d67/src/editors/subscription/later-binding/ext-ref-later-binding-list.ts#L136-L148

Specifically in L141: `this.sameAttributeValue(extRefElement, 'prefix') && `.

When we do the comparison:

the FCDA might be:

```xml
<FCDA ldInst="Application" prefix="" lnClass="LPHD" lnInst="1" doName="Sim" fc="ST" />
```

And the ExtRef might be something like (not an exact match):

```xml
<ExtRef desc="RxPos1" intAddr="RxPos1;/Pos/stVal" pServT="GOOSE" pDO="Pos" pDA="stVal" iedName="XAT_232_M2" ldInst="CB1" lnClass="XCBR" lnInst="1" doName="Pos" daName="stVal" serviceType="GOOSE" srcLDInst="CB1" srcLNClass="LLN0" srcCBName="Ind_0" />
```

Note, there is no prefix. This is optional and the default is the empty string in the standard:

![image](https://user-images.githubusercontent.com/674783/193393432-efc0482f-3fa9-44df-9e51-ba6cfb5d930c.png)

What we do is:

```js
  private sameAttributeValue(
    extRefElement: Element,
    attributeName: string
  ): boolean {
    return (
      extRefElement.getAttribute(attributeName) ===
      this.currentSelectedFcdaElement?.getAttribute(attributeName)
    );
  }
```

Where: `extRefElement.getAttribute(attributeName)` = null (there is no prefix is the extRef)
And `this.currentSelectedFcdaElement?.getAttribute(attributeName)` = `""`

So what happens is we end up comparing `null` with an empty string which fails and so the subscribed ExtRef is not shown.

Do we need to compare the prefix? Is the FCDA fully qualified without it if it is an optional field?
