### ISSUE TITLE
Support ldName attribute

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#1326]
As a user of OpenSCD I want to use functional naming in order to create vendor independent SCD files consisting virtual IEDs without referring to IED name+LDinst attributes.

**Comment by JakobVogelsang** [comment]
Hi @BurTah00, there were multiple users interested in this support. It is a bit hard to fully answer what this in particular means. I think it strongly depends on when you are touching the element `LDevice`. Just from the top of my head it could be:
1. Edit it right at the end before exporting by simply editing, the element `LDevice`.  And could add a field `name` next to `inst`. 
2. Create a virtual IED to be shared with vendors. In that case, we need to change the way the plugin `Virtual IED` works.

**Comment by BurTah00** [comment]
Well, I can only foresee a stepwise approach for implementation. 
For a low hanging fruit :  1. "edit it right at the end before exporting" 
![image](https://github.com/openscd/open-scd/assets/78562586/804dee13-dee0-4a99-91db-956bb258d508)
A SIEMENS like UI with "name" field is fine enough. 

In the long run, there is definetely a need for 2. to create ISD (SSD) like files. But 1. is urgent to have for the moment :)

**Comment by JakobVogelsang** [comment]
Top let's do that.

**Comment by Sander3003** [comment]
@DavoodSooran

**Comment by DavoodSooran** [comment]
**Is your feature request related to a problem? Please describe.**

As a 104 Engineer, I aim to modify the **ldName** associated with a particular **LDevice**. Presently, CoMPAS lacks support for this functionality, necessitating the inclusion of ldName configuration within the tool. Below outlines the steps involved in configuring and altering the ldName.

It's important to note that we don't want users to modify the **ldInst** of an LDevice. Changing the ldInst might create inconsistencies across the entire SCD file. Only modifications to ldName are permitted.

**Describe the solution you'd like**

After uploading your selected SCD file, the IED module will display the supported LDevices within an IED. Clicking on the Filter icon in the Filter section will reveal a list of all available IEDs in the SCD. From this list, you can select the appropriate IED as per your needs. Once selected, all the LDevices within that chosen IED will be listed in the IED module.

![IED select](https://github.com/openscd/open-scd/assets/146732918/1d580163-cc00-4974-9196-bb5609d0ff71)


After selecting the desired IED, the IED module will display all the listed LDevices within that IED. At this point, we aim to modify the ldName of these LDevices. To do so, we require an Edit icon, similar to the one shown in the picture below. However, this particular option is currently not visible or selectable within CoMPAS' IED module.

![LdName edit button](https://github.com/openscd/open-scd/assets/146732918/ba34b483-49c7-4a61-9176-22fce3bf740f)

Clicking on the Edit icon situated on the right side of each LDevice section will prompt a new window to appear, enabling you to modify the ldName and Description. It's important to note that we do not permit users to alter the ldInst of an LDevice, as this could cause inconsistencies throughout the entire SCD file. Therefore, the ldInst section is grayed out and disabled to prevent modifications. Only the ldName can be changed.

![LdName_ldInst](https://github.com/openscd/open-scd/assets/146732918/b09d1f8c-43fc-4fee-98ca-b9ca9f8a8c46)

Once the ldName and Description sections are modified, the changes can be saved, and they will be applied to the SCD file. Clicking on the Edit icon located at the top right side of the dialog box is expected to display the selected LDevice on the SCD code page, as shown in the image below:

![SCD code](https://github.com/openscd/open-scd/assets/146732918/709e13f9-8053-4233-acfa-e5677368a26e)

**Comment by DavoodSooran** [comment]
@Stef3st 
I realized I made an error while defining this issue. I've already rectified the problem in the images. The issue was within the Edit Logical Device dialog box, where I suggested displaying the **ldName** and **desc**. However, as per the standard, the LDevice instance will be denoted as **inst** in the SCD file. Hence, including what I requested, **ldInst**, in the Edit Logical Device dialog box would introduce an additional attribute in the SCD file, resembling the following:

![image](https://github.com/openscd/open-scd/assets/146732918/a0933b60-1579-474e-8d5e-e8325d415332)

Therefore, **ldInst** isn't the correct one. In the images provided with the issue, I've already made the change to **inst**. By incorporating this **inst** in the Edit Logical Device dialog box, we can avoid an additional incorrect LDevice instance in the SCD file. The accurate code in the SCD file should now reflect as follows:

![image](https://github.com/openscd/open-scd/assets/146732918/ccddbde7-5e6d-4557-a122-dd15f0c7b05f)

**Comment by Stef3st** [comment]
@DavoodSooran no worries, I already saw that ldInst was suppose to be inst so its already correct in the PR and is set to inst in the SCL 🙂 I do, however, call it ldInst in the dialog because I thought that was the desired name. Do you suggest to change the field title from ldInst to inst in the dialog aswell?

**Comment by DavoodSooran** [comment]
> @DavoodSooran no worries, I already saw that ldInst was suppose to be inst so its already correct in the PR and is set to inst in the SCL 🙂 I do, however, call it ldInst in the dialog because I thought that was the desired name. Do you suggest to change the field title from ldInst to inst in the dialog aswell?

I believe we can keep the ldInst in the dialog box as long as it doesn't alter the SCD file. :-)
