### ISSUE TITLE
Fix release-please workflow

### ISSUE THREAD

**Issue by juancho0202** [openscd/open-scd#1433]
```terminal
npm notice name:          @openscd/core                           
npm notice version:       0.1.1                                   
npm notice filename:      openscd-core-0.1.1.tgz                  
npm notice package size:  22.3 kB                                 
npm notice unpacked size: 90.5 kB                                 
npm notice shasum:        f313b8f8a83d359dcd89cec4d51c945df26053a5
npm notice integrity:     sha512-OwUeWiA6QCMFN[...]fVeloQLBbr5uw==
npm notice total files:   32                                      
npm notice 
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@openscd%2fcore - You cannot publish over the previously published versions: 0.1.1.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2024-02-06T12_05_23_703Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by Stef3st** [comment]
This error arose because the npm publish command got fired whilst still having the same version in the package.json as the one that's already published. A version incrementation would solve this error.
However, The publish command shouldn't be taken place at this point. The publish command should only be fired when a release PR got merged to the main branch.

The following acceptance criteria need to be met in order to complete this issue:
- [ ]  ReleasePlease should only be triggered when a commit to main has changes that are made in the package/core directory or if a commit to main is from a release PR
- [ ] If the commit has package/core changes, a release PR needs to be made
- [ ] If the commit is from a release PR, workflow can continue and publish to NPM
