### ISSUE TITLE
Version info and updating

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#202]
Hi,
I guess at the moment we can not see the version of the software.
It'd be good to be able to see current version.
It is not so clear how to update the software as a user, even it is automatically updated via browser for standalone application, I'm not sure if the software is updated or not.

BR

**Comment by JakobVogelsang** [comment]
Is the information of the specific version of interest or rather the information that you have the latest version? 

I am just asking as we do not give every change in the main a version number but we collect changes introduced in a period of 2-4 weeks and call that a new [release](https://github.com/openscd/open-scd/releases). This procedure allows use to give you the newest changes with little project management overhead. However for sure we could give a hint if the version you are using  does fit to the latest main as a icon in `Extentions`.

@c-dinkel: what do you think?

**Just as an infor**: Since a two weeks you should get the newest version without resetting in the `Extentions`.  Which practically means that you should always be up to date if your machine in online during from time to time.

**Comment by c-dinkel** [comment]
I think we should add an info dialog with the current version and link to wiki and license.

**Comment by BurTah00** [comment]
Obviously every software has a version info when clicked on somewhere. 
During the last month I introduced open SCD to some customers and they asked about this.

**Comment by JakobVogelsang** [comment]
Decided then. We will add an info page including among other the version
