### ISSUE TITLE
fix(plugging): repair broken plugin auto-update mechanism

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#253]
Hi OpenSCD team,
Is it only for me that,
in Firefox at the moment there is no "open project" and "new project" main screen appears.
![image](https://user-images.githubusercontent.com/78562586/125904661-968da973-587e-4b66-b95f-5805b288783f.png)

and also in Chrome;
Even new project is created as Ed.2 then there is no "Add substation" button visible. And the loading bar below ribbon continuously waving.
![image](https://user-images.githubusercontent.com/78562586/125904802-cc4bd595-5f16-4f1f-a0b0-48892a3eda0e.png)

same happens in Edge.

Could you quickly fix this issues or show me a workaround at least for one browser?
Best Regards
Burak

**Comment by Sander3003** [comment]
"loading bar below ribbon continuously waving" some times happens to me as well (using Edge).

**Comment by ca-d** [comment]
I'm sorry @BurTah00 , we currently have broken auto-update functionality for the extensions. Please click "Extensions" in the menu and hit the "Reset" button as a workaround.

**Comment by BurTah00** [comment]
ok thanks. I kindly request to keep auto-update all the time running or this might cause a lot of problems for the users to understand how to handle this situation.
Best Regards

**Comment by ca-d** [comment]
> I kindly request to keep auto-update all the time running

Just to clarify: It is actually our goal to have all our functionality in a working state all the time. When we recently refactored the plugin system in order to give more flexibility to plugin developers, we accidentally broke the system without noticing. Jakob included this issue in our current sprint, so we expect this feature to start working again within the coming two weeks.

**Comment by ca-d** [comment]
@BurTah00 The fix for this issue has been included in current mainline OpenSCD and should go live on https://openscd.github.io within the next five minutes.

I apologize for accidentally breaking this vital piece of functionality, and will make sure that in the future we'll be notified if we break this again. Thank you again for the report, the bug would likely have taken us much longer to notice without it.
