### ISSUE TITLE
Positioning of the bays with short names

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#255]
![image](https://user-images.githubusercontent.com/78562586/126123927-3c2d0a49-a999-48b3-854c-14f415007f7d.png)
Hi, 
There is a UI problem with the bays and the icons if the bay name is too short or too long. Please have a look on the attachment.
Rgds

**Comment by JakobVogelsang** [comment]
Hi, thank you for this input. This is odd and we will have a closer look at it.

**Comment by ca-d** [comment]
This is the currently intended behavior. Bays may be very tall or very short depending on the number of conducting equipment in them, so from the start we're not aiming for all bays being the same height or width.

What you see in your picture happens when some bay names are long enough to protrude into the bay button group at the top right. What happens then is that we push the bay button group one line down (underneath the "add conducting equipment" button) in order to make space for the description.

@BurTah00 what would be your preferred behavior of the substation editor?

**Comment by BurTah00** [comment]
Thanks Christian&Jakob for the replies.
Now I understand. It is a matter of taste so it is Okay, just wanted to understand it is intentional or not.
