### ISSUE TITLE
Usability issues of new symbols (tooltips)

### ISSUE THREAD

**Issue by BurTah00** [openscd/open-scd#289]
![image](https://user-images.githubusercontent.com/78562586/128812280-f4a2c64b-2faa-4571-be15-d9182c208665.png)
The names of the IEDs are not readable. 
Long names start with ... (three dots) and only the ends are shown. Expected to show the beginning of the word.
No tooltip for the names.
Please don't forget to add tooltips for any enhancement that requires reading something.
These two newly add signals also doesn't have tooltips.
Thanks!

**Comment by JakobVogelsang** [comment]
Thanks for sharing your feedback!! Really appreciated!

We actually show by intention the last part of the IED name instead of the beginning, in case the IED name is too long to fully fit the text box. From my experience, the difference in the IED names is rather at the end and the beginning is shared by most IEDs. 
Would it already help you, if there would be a tooltip that displays the whole IED name?

**Comment by BurTah00** [comment]
![image](https://user-images.githubusercontent.com/78562586/128849630-450f780a-0ecb-45a7-b748-4089975e48ee.png)
I liked your approach that the main distinguisher is the ending part of the IED name which differs.
Nevertheless this we can not easily generalize, or we need to check at least 100 projects to do so.
For instance the project I'am working on attached is the name pool.

In any case just a tooltip would solve the problem....
