### ISSUE TITLE
Use different panzoom implementation

### ISSUE THREAD

**Issue by JakobVogelsang** [openscd/open-scd#414]
The panzoom library we currently use is written with `CommonJS` import style and we cannot import is in our tests.

**Comment by Flurb** [comment]
@ca-d gave an option written in Typescript: https://github.com/timmywil/panzoom

But this library isn't compatible with shadow DOM, there is an issue about this: https://github.com/timmywil/panzoom/issues/536

I'm not sure when it can be fixed, maybe we can try to fix it.
Otherwise, I haven't checked other options.

**Comment by Flurb** [comment]
@JakobVogelsang @ca-d This should be fixed in order to continue #403, how do we continue this?

**Comment by JakobVogelsang** [comment]
We decided to not add the test that imports panzoom. So this is not a blocking issue
