### ISSUE TITLE
When undo / redo actions Subscription / SMV plugin, lists are not refreshed

### ISSUE THREAD

**Issue by Flurb** [openscd/open-scd#633]
When undo / redo an action in the GOOSE or SMV plugin, the action is done but the lists are not being refreshed so it looks like the undo / redo didn't work.

**Comment by Sander3003** [comment]
Does this relates to https://github.com/openscd/open-scd/issues/659?

**Comment by dlabordus** [comment]
The problem is caused by the global variable "localState" used in "subscriber-ied-list-goose.ts".
This is probably done because the elements are re-created often.

Maybe a idea is to make "loaclState" a local variable again. And solve it in "publisher-goose-list.ts" by saving the Goose Element selected as global, like in the IED and SLD Editors is done. When the element is created a GooseEvent is fired to also recreated "localState" again. And maybe also handle "null" values in this event to reset and solve #659 also.
When a Document is loaded the global variable can be resetted in "publisher-goose-list.ts".
