### ISSUE TITLE
Switch publisher and subscriber in SV subscription editor

### ISSUE THREAD

**Issue by Sander3003** [openscd/open-scd#767]
**Is your feature request related to a problem? Please describe.**
As a user of OpenSCD I want to have the same experience with the SV and CGE subscription editor, switch between publishers and subscribers
So I have a consistant user interface and interaction and more features in the SV subscirption editor

**Describe the solution you'd like**
Copy the feature of GSE editor into the SV editor:

![image](https://user-images.githubusercontent.com/7427358/169821367-ae04d616-9c02-4ff5-ab6d-ca24816e56b5.png)

**Comment by JakobVogelsang** [comment]
I would rather suggest combining those together. This is way less work as it fits very well together thematically. 
We can easily do that by adding two  more radio buttons saying something like `Show subscriber IED(s) per selected SMV` and `Show subscribed SMV publisher for selected IED`. For the naming @danyill opened another issue already. We can discuss better naming there (#729).

@Sander3003 what do you think about this?

**Comment by Sander3003** [comment]
Keeping them separate is what we discussed yesterday. The main advantage that I see is the possibility to disable SV for example if engineers don't use it in their projects. Another reason are the other options for non-abb methodes. We can always change this later.

**Comment by JakobVogelsang** [comment]
I see yes this is clearly an advantage and if you have decided as a group I am on board. I would use this issue to find a better naming. The reason is that we at the end will have 6 different subscriber plugins, three different type of subscribing techniques times two each for GOOSE and SMV. 
1. Subscription (GOOSE)
2. Subscription (SV)

For now and then later, something like
3. Subscription - Later Binding (GOOSE)
4. Subscription - Later Binding (SV)

and for the other one I do not have any suggestions yet!
