### ISSUE TITLE
Unable to save edited function names or delete functions

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#807]
**Describe the bug**

I am unable to save a change to function or subfunction name.

**To Reproduce**

1. Open the file: `test/testfiles/zeroline/functions.scd` (No. 1 in screenshot)
2. From the functions view click on either a function or subfunction (No. 2/3 in screenshot)
3. Change the name (No. 4 in screenshot)
4. Click Save (No. 5 in screenshot)
5. Notice there was no change or update. Neither are there any console errors.

**Expected behavior**

I should be able to use the edit button to change the name of functions or subfunctions.

**Screenshots**

![image](https://user-images.githubusercontent.com/674783/172037011-8cefaef4-17ac-4346-a45a-0b00b098c021.png)

**Desktop:**
 - OS: Linux, Kubuntu 22.04
 - Browser: Chrome
 - Version: Version 102.0.5005.61 (Official Build) (64-bit)

**Additional context**

None

**Comment by danyill** [comment]
This is also true for the delete action.

**Comment by JakobVogelsang** [comment]
All this has been introduced by the second last commit. We have changed the way plug-in are loaded. Unfortunately we forgot to make sure that with the new loading mechanism the re-render is working properly. You see that when changing to another editor an then back again. The other bugs you have posted, the last once, are basically the same bug. Again sorry and we are on that. Hope to fix it soon.

**Comment by ca-d** [comment]
This "not updating display on changes" issue has been fixed by https://github.com/openscd/open-scd/pull/814 .

However, there were many issues opened for the same bug (e.g. https://github.com/openscd/open-scd/issues/810, https://github.com/openscd/open-scd/issues/813) and only https://github.com/openscd/open-scd/issues/813 was linked, which is why these others are still open. As mentioned [here](https://github.com/openscd/open-scd/issues/810#issuecomment-1150797830), I suggest we close these fixed issues and open new issues for any problems with particular editor plugins that still remain.

**Comment by ca-d** [comment]
Fixed by #814 .
